name: Publish to PyPI

on:
  push:
    tags:
      - "v*"
  sub`: `repo:Mattmorris-dev/netwatch-sec:environment:pypi
    repository`: Mattmorris-dev/netwatch-sec
    repository_owner : Mattmorris-dev
    repository_owner_id : 125585503
    workflow_ref`: Mattmorris-dev/netwatch-sec/.github/workflows/publish.yml@refs/tags/v1.2.0
    job_workflow_ref`: Mattmorris-dev/netwatch-sec/.github/workflows/publish.yml@refs/tags/v1.2.0
    ref`: refs/tags/v1.2.0
environment`: pypi


      

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token:7d631207-d21b-48d6-8ceb-9897d45096ac

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build
        run: python -m pip install --upgrade pip build

      - name: Build wheel and sdist
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
